### ISSUE TITLE
How to get as2 session

### ISSUE THREAD

**Issue by zengxw08** [fperie/open-as2-servlet#2]
Hi fperie，In the MessageSenderHelper class, there is a sendMessage method which has a parameter session how to get?

**Comment by fperie** [comment]
Hello,

If your application runs in a webapp server, you must create a new servlet
as below :

@WebServlet(name = "gdsn-message-receiver", urlPatterns = { "/gdsn-as2" },
initParams = {
    @WebInitParam(name = "configFile", value =
"classpath:/path/path/fileAs2.xml",
    @WebInitParam(name = "baseDirectory", value = ".") })
public class GdsnMessageReceiverServlet extends OpenAs2Servlet
{
    public static final long serialVersionUID = 1L;

    private static final Logger LOGGER =
LoggerFactory.getLogger(GdsnMessageReceiverServlet.class);

    /**
     * {@inheritDoc}
     */
    @Override
    public void init(ServletConfig config) throws ServletException
    {
        super.init(config);
        initWorker();
    }

    @VisibleForTesting
    @Nonnull
    protected IAs2Worker createWorker()
    {
        return new GdsnAs2MessageWorker();
    }

    private void initWorker()
    {
        WorkerRegistrer.registerWorker(createWorker());
        final IAs2Worker worker = WorkerRegistrer.getWorker();
        LOGGER.debug("worker class: {}", worker == null ? "no worker" :
worker.getClass());
        LOGGER.info("worker AS2 initialisation stored with sucess.");
    }
}


Then, you must create a new class which is the worker to process the as2
received message, as below :

/**
 * This worker allows to process a new AS2 message.
 */
public class GdsnAs2MessageWorker implements IAs2Worker
{
    private static final Logger LOGGER =
LoggerFactory.getLogger(GdsnAs2MessageWorker.class);

    public GdsnAs2MessageWorker()
    {

    }

    @SuppressWarnings("null")
    @Override
    public void processMessage(@Nonnull final Session session, @Nonnull
final AS2Message msg)
    {
        String content = null;
        try
        {
            content = readData(msg.getData().getInputStream());
            processMessage(StringUtils.defaultString(content), msg,
session);
        }
        catch (Exception e)
        {
            LOGGER.error("Impossible to get the message content for the
following reason: ", e);
        }
    }

    @VisibleForTesting
    protected String readData(@Nonnull final InputStream is) throws
IOException
    {
        try (final InputStream isFinal = is;
                final BufferedReader buf = new BufferedReader(new
InputStreamReader(isFinal, "UTF-8")))
        {
            // read the first line without move the pointer
            isFinal.mark(100000);

            String firstLine = buf.readLine();
            isFinal.reset();
            // Choice the encoding message
            Matcher matcher = patternXmlEncoding.matcher(firstLine);

            String encoding = "UTF-8";
            if (matcher.matches())
            {
                String encodingFile = matcher.group(1);
                if (StringUtils.isNotBlank(encodingFile) &&
Charset.isSupported(encodingFile))
                {
                    encoding = encodingFile;
                }
            }
            // read the flow
            return IOUtils.toString(isFinal, encoding);
        }
        catch (IOException exp)
        {
            throw exp;
        }
    }

    @VisibleForTesting
    protected void processMessage(@Nonnull final String content, @Nonnull
final AS2Message msg,
            @Nonnull final Session session)
    {
        try (InputStream is = new ByteArrayInputStream(content.getBytes());
PgihFileDTO pgihFile = new PgihFileDTO();)
        {
           processFile(content, msg, session, null);
        }
        catch (PgihFileException | ValidationException | IOException e)
        {
           LOGGER.error("One error occured during the AS2 file storage.",
e);
        }
    }

    @SuppressWarnings("null")
    protected void processFile(@Nonnull final String content, @Nonnull
final AS2Message msg,
            @Nonnull final Session session, MessageSenderHelper msh)
    {
        // ... do work with the message content
    }
}

Fabien

**Comment by zengxw08** [comment]
thank you very much
